In [125]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /opt/homebrew/anaconda3/lib/python3.13/site-packages (2.1.3)

In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [127]:
# we can give an index number or name for our index column, or leave it blank
df = pd.read_csv('/Users/prakashghatani/Desktop/Regis/MSDS692_Practicum 1/WEEK1/data/LoanApprovalPrediction.csv')
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,LP002978,Female,No,0.0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
594,LP002979,Male,Yes,3.0,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
595,LP002983,Male,Yes,1.0,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
596,LP002984,Male,Yes,2.0,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
597,LP002990,Female,No,0.0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [128]:
df.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

# Basic overview

In [129]:
import plotly.express as px
import plotly.graph_objects as go

# =========================
# Basic Overview
# =========================

print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nFirst 5 Rows:")
display(df.head())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
missing_values = df.isnull().sum()
print(missing_values)

# =========================
# Missing Values Plot
# =========================

missing_df = missing_values.reset_index()
missing_df.columns = ["Column", "Missing_Count"]

fig = px.bar(
    missing_df,
    x="Column",
    y="Missing_Count",
    text="Missing_Count",
    title="Missing Values by Column"
)

fig.update_traces(textposition="outside")
fig.show()

# =========================
# Loan Status Count
# =========================

loan_status_count = df["Loan_Status"].value_counts().reset_index()
loan_status_count.columns = ["Loan_Status", "Count"]

print("\nLoan Status Count:")
print(loan_status_count)

fig = px.pie(
    loan_status_count,
    names="Loan_Status",
    values="Count",
    title="Loan Status Distribution",
    hole=0.4
)

fig.show()

# =========================
# Loan Status Percentage
# =========================

loan_status_percent = (
    df["Loan_Status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .reset_index()
)

loan_status_percent.columns = ["Loan_Status", "Percentage"]

print("\nLoan Status Percentage:")
print(loan_status_percent)

fig = px.bar(
    loan_status_percent,
    x="Loan_Status",
    y="Percentage",
    text="Percentage",
    title="Loan Status Percentage"
)

fig.update_traces(textposition="outside")
fig.show()

# =========================
# Gender Count
# =========================

gender_count = df["Gender"].value_counts().reset_index()
gender_count.columns = ["Gender", "Count"]

print("\nGender Count:")
print(gender_count)

fig = px.bar(
    gender_count,
    x="Gender",
    y="Count",
    text="Count",
    title="Gender Distribution"
)

fig.update_traces(textposition="outside")
fig.show()

# =========================
# Education Count
# =========================

education_count = df["Education"].value_counts().reset_index()
education_count.columns = ["Education", "Count"]

print("\nEducation Count:")
print(education_count)

fig = px.bar(
    education_count,
    x="Education",
    y="Count",
    text="Count",
    title="Education Distribution"
)

fig.update_traces(textposition="outside")
fig.show()

# =========================
# Property Area Count
# =========================

property_count = df["Property_Area"].value_counts().reset_index()
property_count.columns = ["Property_Area", "Count"]

print("\nProperty Area Count:")
print(property_count)

fig = px.bar(
    property_count,
    x="Property_Area",
    y="Count",
    text="Count",
    title="Property Area Distribution"
)

fig.update_traces(textposition="outside")
fig.show()

# =========================
# Numerical Summary
# =========================

print("\nNumerical Summary:")
display(df.describe())

# =========================
# Histograms for Numerical Columns
# =========================

numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

for col in numerical_columns:
    fig = px.histogram(
        df,
        x=col,
        nbins=30,
        title=f"Distribution of {col}"
    )

    fig.show()

Rows and Columns: (598, 13)

Column Names:
Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

First 5 Rows:

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

Data Types:
Loan_ID               object
Gender                object
Married               object
Dependents           float64
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

Missing Values:
Loan_ID               0
Gender                0
Married               0
Dependents           12
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Amount_Term     14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

Loan Status Count:
  Loan_Status  Count
0           Y    411
1           N    187

Loan Status Percentage:
  Loan_Status  Percentage
0           Y       68.73
1           N       31.27

Gender Count:
   Gender  Count
0    Male    487
1  Female    111

Education Count:
      Education  Count
0      Graduate    465
1  Not Graduate    133

Property Area Count:
  Property_Area  Count
0     Semiurban    225
1         Urban    198
2         Rural    175

Numerical Summary:

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,586.000000,598.000000,598.000000,577.000000,584.000000,549.000000
mean,0.755973,5292.252508,1631.499866,144.968804,341.917808,0.843352
std,1.007751,5807.265364,2953.315785,82.704182,65.205994,0.363800
min,0.000000,150.000000,0.000000,9.000000,12.000000,0.000000
25%,0.000000,2877.500000,0.000000,100.000000,360.000000,1.000000
50%,0.000000,3806.000000,1211.500000,127.000000,360.000000,1.000000
75%,1.750000,5746.000000,2324.000000,167.000000,360.000000,1.000000
max,3.000000,81000.000000,41667.000000,650.000000,480.000000,1.000000

In [130]:
overview = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})

overview

               Column Data Type  Missing Values  Unique Values
0             Loan_ID    object               0            598
1              Gender    object               0              2
2             Married    object               0              2
3          Dependents   float64              12              4
4           Education    object               0              2
5       Self_Employed    object               0              2
6     ApplicantIncome     int64               0            491
7   CoapplicantIncome   float64               0            283
8          LoanAmount   float64              21            199
9    Loan_Amount_Term   float64              14             10
10     Credit_History   float64              49              2
11      Property_Area    object               0              3
12        Loan_Status    object               0              2

# Approval rate by key categories

In [131]:
import plotly.express as px

# Convert Loan_Status into numeric
# Y = Approved (1), N = Rejected (0)
df["Loan_Status_Num"] = df["Loan_Status"].map({"Y": 1, "N": 0})

# Function to calculate approval rate and plot
def approval_rate_plot(column_name):
    result = (
        df.groupby(column_name, dropna=False)["Loan_Status_Num"]
        .mean()
        .reset_index()
    )

    result["Approval_Rate_%"] = (result["Loan_Status_Num"] * 100).round(2)

    fig = px.bar(
        result,
        x=column_name,
        y="Approval_Rate_%",
        text="Approval_Rate_%",
        title=f"Approval Rate by {column_name}",
        labels={
            column_name: column_name,
            "Approval_Rate_%": "Approval Rate (%)"
        }
    )

    fig.update_traces(textposition="outside")
    fig.update_layout(
        yaxis_range=[0, 100],
        xaxis_title=column_name,
        yaxis_title="Approval Rate (%)"
    )

    fig.show()

    return result[[column_name, "Approval_Rate_%"]]

# Approval rates by important categories
approval_rate_plot("Gender")
approval_rate_plot("Married")
approval_rate_plot("Education")
approval_rate_plot("Self_Employed")
approval_rate_plot("Property_Area")
approval_rate_plot("Credit_History")
approval_rate_plot("Dependents")

   Dependents  Approval_Rate_%
0         0.0            69.23
1         1.0            64.36
2         2.0            76.77
3         3.0            62.50
4         NaN            50.00

# Credit history — dominant predictor

In [132]:
import plotly.express as px

# Convert Loan_Status into numeric
df["Loan_Status_Num"] = df["Loan_Status"].map({"Y": 1, "N": 0})

# Credit history summary
credit_summary = (
    df.groupby("Credit_History")
    .agg(
        Applicants=("Loan_Status_Num", "count"),
        Approved=("Loan_Status_Num", "sum"),
        Approval_Rate=("Loan_Status_Num", "mean")
    )
    .reset_index()
)

# Convert to percentage
credit_summary["Approval_Rate_%"] = (
    credit_summary["Approval_Rate"] * 100
).round(2)

# Display summary table
display(credit_summary)

# ============================
# Plotly Bar Chart
# ============================

fig = px.bar(
    credit_summary,
    x="Credit_History",
    y="Approval_Rate_%",
    text="Approval_Rate_%",
    color="Credit_History",
    title="Loan Approval Rate by Credit History",
    labels={
        "Credit_History": "Credit History",
        "Approval_Rate_%": "Approval Rate (%)"
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    yaxis_range=[0, 100],
    xaxis=dict(type="category")
)

fig.show()

# ============================
# Applicants vs Approved
# ============================

fig2 = px.bar(
    credit_summary,
    x="Credit_History",
    y=["Applicants", "Approved"],
    barmode="group",
    title="Applicants vs Approved by Credit History",
    labels={
        "value": "Count",
        "Credit_History": "Credit History"
    }
)

fig2.show()

   Credit_History  Applicants  Approved  Approval_Rate  Approval_Rate_%
0             0.0          86         7       0.081395             8.14
1             1.0         463       368       0.794816            79.48

# Income, loan amount & loan term patterns

In [133]:
import plotly.express as px
import plotly.graph_objects as go

# Convert Loan_Status into numeric
df["Loan_Status_Num"] = df["Loan_Status"].map({"Y": 1, "N": 0})

# Create Total Income column
df["TotalIncome"] = (
    df["ApplicantIncome"] + df["CoapplicantIncome"]
)

# Income and Loan Summary
income_loan_summary = df.groupby("Loan_Status").agg(
    Applicants=("Loan_Status", "size"),
    Avg_Applicant_Income=("ApplicantIncome", "mean"),
    Median_Applicant_Income=("ApplicantIncome", "median"),
    Avg_Coapplicant_Income=("CoapplicantIncome", "mean"),
    Avg_Total_Income=("TotalIncome", "mean"),
    Median_Total_Income=("TotalIncome", "median"),
    Avg_Loan_Amount=("LoanAmount", "mean"),
    Median_Loan_Amount=("LoanAmount", "median"),
    Avg_Loan_Term=("Loan_Amount_Term", "mean"),
    Median_Loan_Term=("Loan_Amount_Term", "median")
).round(2)

# Display summary table
display(income_loan_summary)

# Reset index for plotting
summary_df = income_loan_summary.reset_index()

# =====================================
# Average Applicant Income
# =====================================

fig1 = px.bar(
    summary_df,
    x="Loan_Status",
    y="Avg_Applicant_Income",
    text="Avg_Applicant_Income",
    color="Loan_Status",
    title="Average Applicant Income by Loan Status"
)

fig1.update_traces(textposition="outside")
fig1.show()

# =====================================
# Average Total Income
# =====================================

fig2 = px.bar(
    summary_df,
    x="Loan_Status",
    y="Avg_Total_Income",
    text="Avg_Total_Income",
    color="Loan_Status",
    title="Average Total Income by Loan Status"
)

fig2.update_traces(textposition="outside")
fig2.show()

# =====================================
# Average Loan Amount
# =====================================

fig3 = px.bar(
    summary_df,
    x="Loan_Status",
    y="Avg_Loan_Amount",
    text="Avg_Loan_Amount",
    color="Loan_Status",
    title="Average Loan Amount by Loan Status"
)

fig3.update_traces(textposition="outside")
fig3.show()

# =====================================
# Loan Term Comparison
# =====================================

fig4 = px.bar(
    summary_df,
    x="Loan_Status",
    y="Avg_Loan_Term",
    text="Avg_Loan_Term",
    color="Loan_Status",
    title="Average Loan Term by Loan Status"
)

fig4.update_traces(textposition="outside")
fig4.show()

# =====================================
# Applicants Count
# =====================================

fig5 = px.pie(
    summary_df,
    names="Loan_Status",
    values="Applicants",
    title="Applicants Distribution by Loan Status",
    hole=0.4
)

fig5.show()

,Applicants,Avg_Applicant_Income,Median_Applicant_Income,Avg_Coapplicant_Income,Avg_Total_Income,Median_Total_Income,Avg_Loan_Amount,Median_Loan_Amount,Avg_Loan_Term,Median_Loan_Term
Loan_Status,,,,,,,,,,
N,187,5509.44,3948.0,1886.08,7395.52,5417.0,151.91,128.5,343.62,360.0
Y,411,5193.43,3750.0,1515.67,6709.10,5416.0,141.92,125.0,341.15,360.0

# Feature correlations with approval

In [134]:
import plotly.express as px
import pandas as pd

# Convert target to numeric
df["Loan_Status_Num"] = df["Loan_Status"].map({"Y": 1, "N": 0})

# Create Total Income feature
df["TotalIncome"] = (
    df["ApplicantIncome"] + df["CoapplicantIncome"]
)

# Select numeric columns
numeric_df = df.select_dtypes(include=["int64", "float64"])

# Correlation with Loan Approval
approval_corr = (
    numeric_df.corr()["Loan_Status_Num"]
    .sort_values(ascending=False)
)

# Convert to dataframe
approval_corr_df = approval_corr.reset_index()
approval_corr_df.columns = ["Feature", "Correlation"]

# Display correlation table
display(approval_corr_df)

# =========================================
# Plotly Correlation Bar Chart
# =========================================

fig = px.bar(
    approval_corr_df,
    x="Feature",
    y="Correlation",
    text="Correlation",
    color="Correlation",
    title="Feature Correlation with Loan Approval"
)

fig.update_traces(
    texttemplate='%{text:.2f}',
    textposition='outside'
)

fig.update_layout(
    xaxis_title="Features",
    yaxis_title="Correlation Value",
    xaxis_tickangle=-45
)

fig.show()

# =========================================
# Heatmap of Numeric Correlations
# =========================================

corr_matrix = numeric_df.corr().round(2)

fig2 = px.imshow(
    corr_matrix,
    text_auto=True,
    aspect="auto",
    title="Correlation Heatmap of Numeric Features"
)

fig2.show()

             Feature  Correlation
0    Loan_Status_Num     1.000000
1     Credit_History     0.557308
2         Dependents     0.003048
3   Loan_Amount_Term    -0.017554
4    ApplicantIncome    -0.025248
5        TotalIncome    -0.051197
6         LoanAmount    -0.055643
7  CoapplicantIncome    -0.058194